### PR TITLE
Make it easier for users to upgrade from < 0.2.0

### PR DESCRIPTION
**Pull request by lhorace**
This will avoid any nasty issues and I've tested this and worksforme (tm).

### CODE REVIEW

**Comment by turtle0x1** [comment]
thanks man looks great would you mind doing it for the 0.3.0 sql ?

**Comment by turtle0x1** [comment]
also could you please update the changelog ? :)

**Comment by lhorace** [comment]
Sure, and what you want me to add in the changelog?

**Comment by turtle0x1** [comment]
Something to the effect of "update sql for smoother upgrade path" (or something like that) under `Unreleased -> Changed`

**Comment by lhorace** [comment]
Will update 0.3.0 after I test the changes

**Comment by lhorace** [comment]
Sitting down and working on this now, I want to make sure the smooth upgrade actually work. https://github.com/lhorace/LxdMosaic/tree/Test020SQL. I am trying to test it from commit https://github.com/turtle0x1/LxdMosaic/commit/4119e7dd6c8e856219a164d768a5f50cb9413ea4. I am rusty with git but I think I got it so far. While I was studying git, I change the DNS for my internal CT, so long story short, when reverted to earlier snapshot. I need to re-upload certs and configure Apache. Nothing communicates without SSL on my Lan even on my local network. So just need to create a snapshot _after_ I upload the certs.

**Comment by lhorace** [comment]
Hey, by any chance, you on Freenode?

**Comment by turtle0x1** [comment]
hey sorry im sick so im kinda sleeping i can hop on chat tommorow ?

**Comment by lhorace** [comment]
I was hoping we can chat off github, but it I don't care. We can continue....

**Comment by turtle0x1** [comment]
I can hop on freenode whenever, just let me know what channel (?)

**Comment by lhorace** [comment]
Don't worry for now budd.

**Comment by lhorace** [comment]
I am sorry it took this long but please keep this pr, do not work it

**Comment by turtle0x1** [comment]
No problem man whenever you get time

**Comment by lhorace** [comment]
I ran the test, doesn't seem I have to make any changes to 0.3.0, the upgrade flow from < to 0.2.0 to 0.3.0 succeeded without any complications. Any other changes you want me to make?

**Comment by lhorace** [comment]
Are you going this anytime soon so I can pull and upgrade properly?

**Comment by turtle0x1** [comment]
ill need to test it and make sure it works as intended, im away for the weekend so it probably wont be until sunday, you can always just run the sql file on your installation followed by running the 0.3.0.sql + git pull

**Comment by lhorace** [comment]
Just a reminder, it'll be good idea to include a upgrade guide. You know what, on second thought, let me make that change anyway. Assuming people pull from master!

**Comment by lhorace** [comment]
If you going to pull this, can I just close this

**Comment by lhorace** [comment]
No report of problems

**Comment by turtle0x1** [comment]
Sorry man ive been mega busy at work and in my personal life, I just haven't had time to review the methods you used (although im sure there valid), You can leave it closed and maybe ill merge at the weekend or something

**Pull request closed without merging**
