### PR TITLE
Access Control

### LINKED ISSUE #119: LXDMosaic should have some sort of access control
**Is your feature request related to a problem? Please describe.**
To be used in production (enterprise or not) LXDMosaic should have some sort of access control limiting who is permitted to manage & orchestrate containers.

**Describe the solution you'd like**
Whatever is implemented for LXDMosaic should  also be able to be integrated with other systems.   Perhaps others might have some ideas here.

**Describe alternatives you've considered**
Perhaps PAM might work if there was a LXDMosaic "group" of permitted users. 

**Additional context**

### PR DESCRIPTION
**Pull request by turtle0x1**
Currently only supports MySQL for user stroage & uses PHP sessions to authenticate everything

This will break any scripts using the API, it will also need to be changed to use a separate auth for the API as scripts don't want sessions! 

close #119

### CODE REVIEW

**Comment by shemgp** [comment]
Do you think it's needed to secure the websockets too or is there no security threat for that?

**Comment by turtle0x1** [comment]
They do need to be secured, its just deciding how~

**Comment by shemgp** [comment]
How about [this](https://devcenter.heroku.com/articles/websocket-security#authentication-authorization) and/or [this](https://www.freecodecamp.org/news/how-to-secure-your-websocket-connections-d0be0996c556/#-4-authenticate-users-before-ws-connection-establishes)?

**Comment by turtle0x1** [comment]
Thanks for the links, they are are on the right track;

Right now this program uses PHP session's exclusively to do auth, which gives the browser a cookie, the cookie is sent to the Node service and in theory all that needs to be done is read the `PHPSESSID` (from the cookie) and then try to read from the session file on the server to authenticate the user.

The problem being, the above doesn't scale past 1 machine, as each instance will keep track of its own cookies, to combat that we have to add an additional service like redis or mem-cached to distribute the sessions, but that increases deployment complexity;

I dont want to force people to use cookies to make API calls to the app, so I need to introduce the concept of "api keys" that can be passed around instead of cookies ("proper" REST) but honestly .. I am being  kinda lazy (I have a large amount of "real" (paid) work todo & Auth has never really been of great personal interest to me)

**Comment by shemgp** [comment]
How about:
1. once authenticated via php session, generate a token
2. save the token to the database
3. pass the token to js when so that when the browser uses websockets the token will be in the cookie
4. in the websocket server receive the token and check the database if the token is valid

Do you think that will work? I might find time to create a PR if you think it's feasible.

**Comment by turtle0x1** [comment]
That in a nut shell is exactly what needs to happen,

I would be very open to any PR (and chiming in here and there if you need help) :smile:

**Comment by bmullan** [comment]
A quick search of Github for "php sso" returned:

https://github.com/search?q=php+sso

Perhaps one of those might be adapted for LXDMosaic?

**Comment by turtle0x1** [comment]
Hey Brian, 

Thanks for the input but it would appear that library is very out of date in terms of PHP development practises (even by my standards :laughing:)

Im trying to minimize the number of external services like apache2, redis or the proposed `php-sso` server, which is why we are going todo custom auth (for the time being)

As I said above though, its more about laziness than anything, what me & @shemgp are proposing is good enough for now :smile:

**Pull request merged**
