### PR TITLE
Change Crunz vendor

### PR DESCRIPTION
**Pull request by PabloKowalczyk**
Crunz changed repository: https://github.com/lavary/crunz/issues/411

### CODE REVIEW

**Comment by turtle0x1** [comment]
Thanks very much for this!

Symfony carries some weight in the community (I.E they can ask Github), have you tried every avenue to rescue the 1400 star repo you have? Changing over to a very low star repo seems like it could cause unnecessary concern.

Using `git diff` its clear you haven't poisoned the repo but i'm "scared" to merge this change.

Thanks

**Comment by turtle0x1** [comment]
Well @fabpot the leader of `symfony` project has accepted this so... I will as well.

**Comment by turtle0x1** [comment]
For those interested, here is the link https://github.com/symfony/marketing/pull/547

**Comment by PabloKowalczyk** [comment]
Hello,

> Symfony carries some weight in the community (I.E they can ask Github), have you tried every avenue to rescue the 1400 star repo you have?

Actually it's not my repo this is why I can't do much there. Tried to contact @lavary but without response.

> Using git diff its clear you haven't poisoned the repo but i'm "scared" to merge this change.

That's understandable and all I can do is to advise installing https://github.com/pyrech/composer-changelogs to show links to diff after every `update`, with this you can quickly check every dependency changes.

Also, I was maintainer of https://github.com/lavary/crunz, now I focus on https://github.com/crunzphp/crunz, so only repo name changed :)

**Pull request merged**
